[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "applyai"
version = "0.1.0"
description = "AI-powered job application assistant"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["app"]