# secrets.toml
# Sensitive configuration for Job Buddy application
# IMPORTANT: Add this file to .gitignore to prevent committing sensitive data

# Anthropic API Configuration
ANTHROPIC_API_KEY = "your_anthropic_api_key_here"

# Database Configuration
DB_PATH = "job_buddy.db"

# Optional: Development/Test Credentials (NOT recommended for production)
# USERNAME = "dev_user"
# PASSWORD = "dev_password"

# Optional: External Service Credentials
# OPENAI_API_KEY = "your_openai_key_if_needed"
# HUGGINGFACE_TOKEN = "your_huggingface_token_if_needed"

# Logging Configuration
LOG_LEVEL = "INFO"